apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saas-backend.fullname" . }}-secret
  labels:
    {{- include "saas-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  CELERY_BROKER_URL: {{ .Values.secrets.celeryBrokerUrl | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.secrets.celeryResultBackend | quote }}
  {{- if .Values.secrets.googleClientId }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientId }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.microsoftClientId }}
  MICROSOFT_CLIENT_ID: {{ .Values.secrets.microsoftClientId | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.secrets.microsoftClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.keycloakClientSecret }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  AWS_S3_BUCKET: {{ .Values.secrets.awsS3Bucket | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- if .Values.secrets.smtpUser }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  SMTP_FROM: {{ .Values.secrets.smtpFrom | quote }}
  {{- end }}
  {{- if .Values.secrets.sentryDsn }}
  SENTRY_DSN: {{ .Values.secrets.sentryDsn | quote }}
  {{- end }}
