apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-backend.fullname" . }}-api
  labels:
    {{- include "saas-backend.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saas-backend.selectorLabels" . | nindent 4 }}
    component: api
