apiVersion: v2
name: saas-backend
description: Production-grade SaaS backend framework with FastAPI
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - fastapi
  - saas
  - backend
  - api
  - python
home: https://github.com/yourusername/saas-backend
sources:
  - https://github.com/yourusername/saas-backend
maintainers:
  - name: Your Name
    email: your-email@example.com

dependencies:
  # PostgreSQL subchart (optional)
  - name: postgresql
    version: "13.2.24"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database

  # Redis subchart (optional)
  - name: redis
    version: "18.4.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache

  # MinIO subchart (optional)
  - name: minio
    version: "5.0.15"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
    tags:
      - storage
